ex078: main.o array_sort1.o
	gcc -g -Wall main.o array_sort1.o -o ex078
	
main.o: main.c
	gcc -g -Wall -c main.c -o main.o
	
array_sort1.o: array_sort1.c
	gcc -g -Wall -c array_sort1.c -o array_sort1.o
	
run: ex078
	./ex078
