ex06: main.o power_ref.o
	gcc -g -Wall main.o power_ref.o -o ex06
	
main.o: main.c
	gcc -g -Wall -c main.c -o main.o
	
sum_even.o: sum_even.c
	gcc -g -Wall -c power_ref.c -o power_ref.o
	
run: ex06
	./ex06
